name: Trigger auto deployment for pioneers-api

on:
    workflow_run:
        workflows: ['Validate Code Quality']
        types:
            - completed
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        permissions:
            id-token: write
            contents: read
            packages: write # Required to push to GitHub Container Registry

        steps:
            - name: Checkout to the branch
              uses: actions/checkout@v4

            - name: Azure Login
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.PIONEERSAPI_AZURE_CLIENT_ID }}
                  tenant-id: ${{ secrets.PIONEERSAPI_AZURE_TENANT_ID }}
                  subscription-id: ${{ secrets.PIONEERSAPI_AZURE_SUBSCRIPTION_ID }}

            - name: Build and push image to GitHub Registry
              uses: azure/container-apps-deploy-action@v2
              with:
                  appSourcePath: ${{ github.workspace }}
                  dockerfilePath: Containerfile
                  # Use GitHub's registry
                  registryUrl: ghcr.io
                  registryUsername: ${{ github.actor }}
                  registryPassword: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub
                  containerAppName: pioneers-api
                  resourceGroup: pioneer
                  imageToBuild: ghcr.io/${{ github.repository_owner }}/pioneers-api:${{ github.sha }}
